### ISSUE TITLE
Search does not work on sample file BasicNetworkWithAnnotation.cyjs

### ISSUE THREAD

**Issue by BarbaNikos** [bd2kccd/ccd-annotations-cytoscape#36]
I import file "BasicNetworkWithAnnotation.cyjs" that comes with the following annotations:

- Edges
- Nodes 1 and 3
- Nodes 2 and 3

First of all, the UI for Searching looks distorted, Since the text "Filter" and its accompanying text for "Value", drop-down box for (in-)equality, and textbox are on another line. 

When I fill out the Name "Edges" and press the Search button, nothing appears on the results. 

In addition, if I select an element, add an annotation with a value, and then search for it, it doesn't appear on the results. This is a bug that doesn't throw any exceptions.

**Comment by marksilvis** [comment]
I believe that the `BasicNetworkWithAnnotation.cyjs` file is old. I will double check and remove it if so.
