### ISSUE TITLE
Cytoscape node/edge tables not updated correctly

### ISSUE THREAD

**Issue by marksilvis** [bd2kccd/ccd-annotations-cytoscape#38]
When creating an annotation, the Cytoscape table should be updated so that the relevant nodes and edges are linked to the new annotation. Currently, it seems that the first annotation is added to ALL graph components, then subsequently added annotations are not added to any.

**Comment by BarbaNikos** [comment]
In `SimpleNetwork.cyjs` the nodes have the following SUIDs:

- Node D, SUID: 74
- Node C, SUID: 68
- Node B, SUID: 66
- Node A, SUID: 64

However, when I inspect the code executed in `edu.pitt.cs.admt.cytoscape.annotations.network.NetworkListener.handleEvent(final NetworkViewAddedEvent event)` the list of nodes retrieved (with a call to `getNodes(final CyNetwork network)`), have different SUIDs. In detail, the SUIDs become:

- 65
- 64
- 63
- 62

As a result, this error escalates and all of the _CCD_Annotation_Set column gets mixed up. I am not entirely sure yet, but in the database the values are updated properly. However, when I export the file, after attempting to add an integer valued annotation to Nodes B and C (named tt with a value of 12), I get the following output:

`{
  "format_version" : "1.0",
  "generated_by" : "cytoscape-3.6.0",
  "target_cytoscapejs_version" : "~2.1",
  "data" : {
    "shared_name" : "SimpleNetwork",
    "__Annotations" : [ "canvas=foreground|color=-16777216|zoom=1.0|type=org.cytoscape.view.presentation.annotations.TextAnnotation|fontStyle=0|uuid=24c51dbc-d39b-430d-bbbb-5ca197f846cd|fontFamily=Arial|name=TextAnnotation_0|x=-525.0|y=-88.0|z=-1|fontSize=16|text=TEST", "canvas=foreground|color=-16777216|zoom=1.0|type=org.cytoscape.view.presentation.annotations.TextAnnotation|fontStyle=0|uuid=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|fontFamily=Arial|name=TextAnnotation_1|x=-359.40089759188265|y=-103.7066068272078|z=-1|fontSize=12|text=tt: 12" ],
    "name" : "SimpleNetwork",
    "SUID" : 52,
    "shared_name" : "SampleNetwork",
    "__CCD_Annotations" : [ "", "uuid=80def39b-38b7-4271-9a23-7af8f43f2397|name=tt|type=INT|description=adf" ],
    "selected" : true
  },
  "elements" : {
    "nodes" : [ {
      "data" : {
        "id" : "65",
        "shared_name" : "Node A",
        "name" : "Node A",
        "SUID" : 65,
        "shared_name" : "Node A",
        "id_original" : "64",
        "__CCD_Annotation_Set" : [ "", "uuid=80def39b-38b7-4271-9a23-7af8f43f2397|name=tt|type=INT|description=adf", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12" ],
        "selected" : false
      },
      "position" : {
        "x" : -505.0,
        "y" : -114.0
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "64",
        "shared_name" : "Node B",
        "name" : "Node B",
        "SUID" : 64,
        "shared_name" : "Node B",
        "id_original" : "66",
        "__CCD_Annotation_Set" : [ "", "uuid=80def39b-38b7-4271-9a23-7af8f43f2397|name=tt|type=INT|description=adf", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12" ],
        "selected" : true
      },
      "position" : {
        "x" : -359.0,
        "y" : -40.0
      },
      "selected" : true
    }, {
      "data" : {
        "id" : "63",
        "shared_name" : "Node C",
        "name" : "Node C",
        "SUID" : 63,
        "shared_name" : "Node C",
        "id_original" : "68",
        "__CCD_Annotation_Set" : [ "", "uuid=80def39b-38b7-4271-9a23-7af8f43f2397|name=tt|type=INT|description=adf", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12" ],
        "selected" : true
      },
      "position" : {
        "x" : -359.0,
        "y" : -167.0
      },
      "selected" : true
    }, {
      "data" : {
        "id" : "62",
        "shared_name" : "Node D",
        "name" : "Node D",
        "SUID" : 62,
        "shared_name" : "Node D",
        "id_original" : "74",
        "__CCD_Annotation_Set" : [ "", "uuid=80def39b-38b7-4271-9a23-7af8f43f2397|name=tt|type=INT|description=adf", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12" ],
        "selected" : false
      },
      "position" : {
        "x" : -220.0,
        "y" : -99.0
      },
      "selected" : false
    } ],
    "edges" : [ {
      "data" : {
        "id" : "69",
        "source" : "65",
        "target" : "64",
        "shared_name" : "Node A (interacts with) Node B",
        "shared_interaction" : "interacts with",
        "shared_interaction" : "interacts with",
        "name" : "Node A (interacts with) Node B",
        "interaction" : "interacts with",
        "SUID" : 69,
        "source_original" : "64",
        "shared_name" : "Node A (interacts with) Node B",
        "id_original" : "70",
        "__CCD_Annotation_Set" : [ "", "uuid=80def39b-38b7-4271-9a23-7af8f43f2397|name=tt|type=INT|description=adf", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12" ],
        "selected" : false,
        "target_original" : "66"
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "68",
        "source" : "64",
        "target" : "63",
        "shared_name" : "Node B (interacts with) Node C",
        "shared_interaction" : "interacts with",
        "shared_interaction" : "interacts with",
        "name" : "Node B (interacts with) Node C",
        "interaction" : "interacts with",
        "SUID" : 68,
        "source_original" : "66",
        "shared_name" : "Node B (interacts with) Node C",
        "id_original" : "72",
        "__CCD_Annotation_Set" : [ "", "uuid=80def39b-38b7-4271-9a23-7af8f43f2397|name=tt|type=INT|description=adf", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12" ],
        "selected" : false,
        "target_original" : "68"
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "67",
        "source" : "64",
        "target" : "62",
        "shared_name" : "Node B (interacts with) Node D",
        "shared_interaction" : "interacts with",
        "shared_interaction" : "interacts with",
        "name" : "Node B (interacts with) Node D",
        "interaction" : "interacts with",
        "SUID" : 67,
        "source_original" : "66",
        "shared_name" : "Node B (interacts with) Node D",
        "id_original" : "78",
        "__CCD_Annotation_Set" : [ "", "uuid=80def39b-38b7-4271-9a23-7af8f43f2397|name=tt|type=INT|description=adf", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12" ],
        "selected" : false,
        "target_original" : "74"
      },
      "selected" : false
    }, {
      "data" : {
        "id" : "66",
        "source" : "63",
        "target" : "62",
        "shared_name" : "Node C (interacts with) Node D",
        "shared_interaction" : "interacts with",
        "shared_interaction" : "interacts with",
        "name" : "Node C (interacts with) Node D",
        "interaction" : "interacts with",
        "SUID" : 66,
        "source_original" : "68",
        "shared_name" : "Node C (interacts with) Node D",
        "id_original" : "76",
        "__CCD_Annotation_Set" : [ "", "uuid=80def39b-38b7-4271-9a23-7af8f43f2397|name=tt|type=INT|description=adf", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12", "a_id=80def39b-38b7-4271-9a23-7af8f43f2397|cy_id=8b4f713b-354c-48ad-ab7a-5b6fda7427e3|value=12" ],
        "selected" : false,
        "target_original" : "74"
      },
      "selected" : false
    } ]
  }
}`

Therefore, two things need to be done in my opinion: 

1. The values shown in the network table need to be updated with the new SUIDs.
2. Verify that the export functionality is done in the correct manner.

**Comment by BarbaNikos** [comment]
After researching further, the renaming of nodes' SUIDs takes place when the network gets parsed. In detail, after remote debugging `NetworkListener.handleEvent(final NetworkViewAddedEvent event)` (line 76) I see that the nodes have their SUIDs renamed already. The same happens for edges and the network itself. 

In other words, this is a big problem because until now we have assumed that SUIDs remain the same. However, this is not the case and Cytoscape changes those values when a file gets imported. Also, I don't think we support changes in the SUIDs by the users. This might also be a problem because when exporting a file, the SUIDs in the database will not be consistent with the SUIDs on the Network.

**Comment by BarbaNikos** [comment]
This error does not cause any further problems since SUIDs get updated and match the annotations' UUIDs. However, the Node/Edge table values remain outdated in the Network View
