### ISSUE TITLE
Database query fetch nodes/edges per Cytoscape UUID

### ISSUE THREAD

**Issue by marksilvis** [bd2kccd/ccd-annotations-cytoscape#42]
I need a database query that takes a Cytoscape annotation UUID and returns the nodes (and edges) that are associated with that annotation. The purpose of this is to quickly re-layout the annotation(s) based on the location of the components that it's annotating.

**Comment by BarbaNikos** [comment]
This feature is added on the develop branch. It is `StorageDelegate.getNetworkComponentsOnCytoscapeAnnotUUID()`. It returns a collection of integers with the corresponding SUIDs (both nodes and edges).
