### ISSUE TITLE
Automatically re-layout annotations

### ISSUE THREAD

**Issue by marksilvis** [bd2kccd/ccd-annotations-cytoscape#48]
Now that annotations can be re-layout with a button press, we should look into doing it automatically. Ideally, this will be a setting that can be turned on or off in the menu.

Look into `CyListener` classes that handle visual property changes.

**Comment by marksilvis** [comment]
We may want to consider an additional query to support this. Provided a node or edge SUID, I want a collection of `AnnotToEntities` that are attached to said node/edge.

**Comment by marksilvis** [comment]
Also, I will re-add the manual option.

**Comment by marksilvis** [comment]
Manual option reintroduced. Automatic option is toggle-able. Waiting on queries to improve performance (avoid iteration over all annotations), then I can finish this task.

**Comment by BarbaNikos** [comment]
Done. I added: 
* `StorageDelegate.getAnnotationOnNode(final long networkSUID, final int nodeSUID)` 
* `StorageDelegate.getAnnotationOnEdge(final long networkSUID, final int edgeSUID)`
* `StorageDelegate.getAnnotationToEntities(final long networkSUID, Collection<Integer> nodes, Collection<Integer> edges)`

The first two return a `Set<AnnotToEntity>` for all the annotations attached to a given node/edge. The third one returns a `Set<AnnotToEntity>` representing the union of annotations for the given nodes and edges.

**Comment by marksilvis** [comment]
I will update the layout manager to use your methods

**Comment by marksilvis** [comment]
Done. Also, I fixed most of the visual jitteriness when re-layouting annotations.
